### ISSUE TITLE
Task 0. Github и Git. Init

### ISSUE THREAD

**Issue by yarigpopov** [new-hope/spec#1]
- [x] Create in `new hope` organization repository with the name `git-sandbox`
- [x]  Initialize  repository `git-sandbox` 
- [ ]  Clone   `git-sandbox` at local computer
- [ ]  Create file `foo.txt` with text `Hello world`
- [ ]  Commit changes to the `master` branch
- [ ]  Push commit to `github`

**Comment by yarigpopov** [comment]
@Grishchenko а на клонировании и прочем застрял?

**Comment by Grishchenko** [comment]
Не не застрял. Сделал. Щас на работу убегаю. Седня вечером выложу все.

**Comment by Grishchenko** [comment]
Слав, привет. Не могу залить на гитхаб. Делал так:
1. Клонировал 
git clone https://github.com/new-hope/git-sandbox
Все ок.
2. Создал файл и добавил его в локальный репозиторий
git add foo.txt
Все ок.
3. Закоммитил
git commit - m "Hi"
все ок. 
4.  Потом определяю удаленный репозиторий
git remote add origin https://github.com/new-hope/git-sandbox
все ок.
5. git push -u origin master
Тут не ок.
Что я не так делаю?

**Comment by yarigpopov** [comment]
А какая ошибка?

**Comment by Grishchenko** [comment]
![default](https://cloud.githubusercontent.com/assets/21172641/19185441/557e3fb6-8c8a-11e6-9d77-577b1d93b551.png)

**Comment by Grishchenko** [comment]
![default](https://cloud.githubusercontent.com/assets/21172641/19185745/a2a9c778-8c8b-11e6-9baa-3f04a0f74d9d.png)
