### ISSUE TITLE
Task 1. Github и Git. Basic

### ISSUE THREAD

**Issue by yarigpopov** [new-hope/spec#2]
Pre: do this task after [task 0](https://github.com/new-hope/spec/issues/1)
- [ ] read about github-flow ( [here in rus](https://habrahabr.ru/post/106912/))
- [ ]  in repository `git-sandbox` create a branch `issues/2-basic-operations` from the branch `master`
- [ ]  in 'foo.txt' add line 'The weather is awesome!' and commit
- [ ]  push the branch to github
- [ ]  open (Pull request)[https://help.github.com/articles/creating-a-pull-request/] to the master branch and assign me to it

**Comment by Grishchenko** [comment]
Слав, привет. Хочу уточнить:
Изменения в файле нужно проделать в новой ветке и добавить  ее на гитхаб?
