### ISSUE TITLE
Deploy Animations tutorial

### ISSUE THREAD

**Issue by yarigpopov** [new-hope/spec#7]
Please deploy resulting tutorial code
https://github.com/new-hope/BuildAppCSSAnimations

so it could be accessible like
https://new-hope.github.io/BlastingOffwithBootstrap/

to accomplish this task you google for `deploy github pages`

**Comment by Grishchenko** [comment]
https://new-hope.github.io/BuildAppCSSAnimations/

**Comment by yarigpopov** [comment]
Да ты ж молодец!
